Submit post w/ cloudinary ref and userId containing placenholders
iamdp/r8it pull request #21
Opened 2018-11-15 20:15 UTC by tleytek

2018-11-15 20:21 UTC, tleytek commented
The additions and deletions are so big because my PR doesn't have semantic versioning for some reason?

2018-11-15 20:38 UTC, VishnuSwaminathan submitted a review, later dismissed

2018-11-16 16:11 UTC, iamdp commented
FYI, your code is great. I'm going through and nit-picking and making comments from a learning perspective.

2018-11-16 16:28 UTC, iamdp requested changes

2018-11-16 16:28 UTC, iamdp commented on routes/someRoutes.js
> +  //Just wanted to try object desctructuring
A+, always be trying new things! Programmer mentality!

2018-11-16 16:28 UTC, iamdp commented on routes/someRoutes.js
> +  } = req.body;
If the value name is equal to the variable name, you can leave out the assignment. For example
`let {title, eloRank, etc} = req.body`

2018-11-16 16:28 UTC, iamdp commented on routes/someRoutes.js
> +    eloRank: eloRank,
I think it would be better to ensure that eloRank is assigned by the server instead of the client. So i'd change this to `eloRank: 0`

2018-11-16 16:28 UTC, iamdp commented on routes/someRoutes.js
> +  let {
If were not reassigning the value of the variable, we can assign the variable to a `const`

2018-11-16 16:28 UTC, iamdp commented on routes/someRoutes.js
> +
We should make a response here. If we don't the client will just hang. `res.send(something)`

2018-11-16 16:28 UTC, iamdp commented on controller/controller.js
> +      if (err) return handleError(err);
`if (err)` should come before `console.log(res)` because if there's an error, the `res` will be undefined and the app will break before the error is returned.

2018-11-16 16:28 UTC, iamdp commented on controller/controller.js
> +  submitPost: postData => {
This route is the first of it's kind, being the only route to create data. What's unique to this is we should be adding some error handling here. Making sure the data is correct. Alternatively we can rely on the database and model to handle these errors, but we also need to report it back to the client.

2018-11-16 16:28 UTC, iamdp commented on client/src/components/r8it/submit.js
> +        challengeId: response.data[0]._id
All the data we need is in the previous line, there should be no need to duplicate data here.

2018-11-16 16:28 UTC, iamdp commented on client/src/components/r8it/submit.js
> +                value={this.state.title}
not necessary

2018-11-16 16:28 UTC, iamdp commented on client/src/components/r8it/submit.js
> +                value={this.state.description}
not necessary

2018-11-16 16:28 UTC, iamdp commented on client/src/components/r8it/submit.js
> +    challengeId: ""
We'll let the db assign the challengeId, no need to add this field to state.

2018-11-17 18:34 UTC, iamdp approved these changes

2018-11-17 18:35 UTC, merged